### ISSUE TITLE
Can not install npm on bamboo via maven

### ISSUE THREAD

**Issue by jeiroa** [eirslett/frontend-maven-plugin#224]
Hi,

I am trying to execute the maven goal clean install on bamboo CI server and I get this error:

[INFO] ` /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node ` exists.
[INFO]  testing binary.
[INFO] Binary is fine; exiting.
[INFO] 
[INFO] > gravity-central-control-ui@0.0.0 postinstall /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1
[INFO] > cd node_modules/qTip2 && npm run build
[INFO] 
[ERROR] sh: 1: npm: Permission denied
[ERROR] 
[ERROR] npm ERR! gravity-central-control-ui@0.0.0 postinstall: `cd node_modules/qTip2 && npm run build`
[ERROR] npm ERR! Exit status 127
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the gravity-central-control-ui@0.0.0 postinstall script.
[ERROR] npm ERR! This is most likely a problem with the gravity-central-control-ui package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     cd node_modules/qTip2 && npm run build
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls gravity-central-control-ui
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! System Linux 3.11.0-17-generic
[ERROR] npm ERR! command "/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/node" "/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! cwd /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1
[ERROR] npm ERR! node -v v0.10.38
[ERROR] npm ERR! npm -v 1.4.28
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! 
[ERROR] npm ERR! Additional logging details can be found in:
[ERROR] npm ERR!     /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/npm-debug.log
[ERROR] npm ERR! not ok code 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:02 min
[INFO] Finished at: 2015-06-03T13:36:38+00:00
[INFO] Final Memory: 15M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (npm install) on project esp-ui: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (npm install) on project esp-ui: Failed to run task
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failed to run task
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:62)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'npm install --color=false' failed. (error code 1)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeTaskExecutor.execute(NodeTaskExecutor.java:38)
	at com.github.eirslett.maven.plugins.frontend.mojo.NpmMojo.execute(NpmMojo.java:59)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
simple	03-Jun-2015 14:36:38	Failing task since return code of [/opt/apache-maven-3.2.1/bin/mvn --batch-mode -Djava.io.tmpdir=/tmp/ESPCC-UI-JOB1 clean install -X] was 1 while expected 0

This is the final part of the npm-debug.log:

115828 info gravity-central-control-ui@0.0.0 Failed to exec postinstall script
115829 error gravity-central-control-ui@0.0.0 postinstall: `cd node_modules/qTip2 && npm run build`
115829 error Exit status 127
115830 error Failed at the gravity-central-control-ui@0.0.0 postinstall script.
115830 error This is most likely a problem with the gravity-central-control-ui package,
115830 error not with npm itself.
115830 error Tell the author that this fails on your system:
115830 error     cd node_modules/qTip2 && npm run build
115830 error You can get their info via:
115830 error     npm owner ls gravity-central-control-ui
115830 error There is likely additional logging output above.
115831 error System Linux 3.11.0-17-generic
115832 error command "/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/node" "/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/npm/bin/npm-cli.js" "install" "--color=false"
115833 error cwd /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1
115834 error node -v v0.10.38
115835 error npm -v 1.4.28
115836 error code ELIFECYCLE
115837 verbose exit [ 1, true ]

I found out that npm can not be found (it is not globally installed in the elastic instance) so I added /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/npm/bin to PATH and now the error is:

[INFO] > gravity-central-control-ui@0.0.0 postinstall /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1
[INFO] > cd node_modules/qTip2 && npm run build
[INFO] 
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module '/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/npm/bin/node_modules/npm/bin/npm-cli.js'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Function.Module.runMain (module.js:497:10)
[ERROR]     at startup (node.js:119:16)
[ERROR]     at node.js:935:3
[ERROR] 
[ERROR] npm ERR! gravity-central-control-ui@0.0.0 postinstall: `cd node_modules/qTip2 && npm run build`
[ERROR] npm ERR! Exit status 8
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the gravity-central-control-ui@0.0.0 postinstall script.
[ERROR] npm ERR! This is most likely a problem with the gravity-central-control-ui package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     cd node_modules/qTip2 && npm run build
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls gravity-central-control-ui
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! System Linux 3.11.0-17-generic
[ERROR] npm ERR! command "/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/node" "/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/node/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! cwd /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1
[ERROR] npm ERR! node -v v0.10.38
[ERROR] npm ERR! npm -v 1.4.28
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! 
[ERROR] npm ERR! Additional logging details can be found in:
[ERROR] npm ERR!     /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-JOB1/npm-debug.log
[ERROR] npm ERR! not ok code 0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.377 s
[INFO] Finished at: 2015-06-03T13:50:09+00:00
[INFO] Final Memory: 26M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (npm install) on project esp-ui: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]

It seems path to npm-cli.js is wrong.

It is working in my local machine (Ubuntu 14.04) but if I npm I get the same errors.

pom.xml section is:
<plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>0.0.23</version>
        <executions>
            <execution>
                
                <id>install node and npm</id>
                <goals>
                    <goal>install-node-and-npm</goal>
                </goals>
                
                <phase>generate-resources</phase>
                <configuration>
                    <nodeVersion>v0.10.38</nodeVersion>
                    <npmVersion>1.4.28</npmVersion>
                    
                    
                </configuration>
            </execution>
            <execution>
                <id>npm install</id>
                <goals>
                    <goal>npm</goal>
                </goals>

                
                <phase>generate-resources</phase>

                <configuration>
                    
                    <arguments>install</arguments>
                </configuration>
            </execution>
            <execution>
                <id>gulp build</id>
                <goals>
                    <goal>gulp</goal>
                </goals>

                
                <phase>generate-resources</phase>

                <configuration>
                    
                    <arguments>build --production</arguments>
                </configuration>
            </execution>
        </executions>
    </plugin>

  I do not know how to solve the issue. Can someone help me, please?

  Thanks.

**Comment by eirslett** [comment]
Try copying the helper script for npm (npm and npm.cmd) into your project root directory - the same directory as the pom.xml file?
That could have the effect of overriding the npm executable maven is trying to use.

**Comment by jeiroa** [comment]
I am sorry, I misspelled a sentence before. What I wanted to say is that the process works fine if I have npm installed but if I uninstall it I get the errors. I am doing this because I cannot install npm on the default installation of the CI server.

I tried what you say and I am getting the first error (npm: Permission denied, npm ERR! Exit status 127). If I execute npm from the project root directory I get ./npm: 13: ./npm: node: not found

Do you need more information?

Thanks for your time.

**Comment by eirslett** [comment]
Did you use the npm script from the frontend-maven-plugin? Or from the default npm bubdle?

**Comment by jeiroa** [comment]
I copied ${root}/node/npm/node/bin/npm file into ${project.root} and then I executed mvn clean install from ${project.root}. I also executed ./npm from ${project.root} only to test I have correct execution permission for that file.

  Did I copy the wrong file into the wrong folder? Do you need more information?

**Comment by eirslett** [comment]
Try these: https://github.com/eirslett/frontend-maven-plugin/tree/master/frontend-maven-plugin/src/it/example%20project/helper-scripts

**Comment by jeiroa** [comment]
I have copied these scripts into ${project.root} and executed mvn clean install but I am still getting this error:

[ERROR] sh: 1: npm: Permission denied
[ERROR] 
[ERROR] npm ERR! gravity-central-control-ui@0.0.0 postinstall: `cd node_modules/qTip2 && npm run build`
[ERROR] npm ERR! Exit status 127
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the gravity-central-control-ui@0.0.0 postinstall script.
[ERROR] npm ERR! This is most likely a problem with the gravity-central-control-ui package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     cd node_modules/qTip2 && npm run build
[ERROR] npm ERR! You can get their info via:
[ERROR] npm ERR!     npm owner ls gravity-central-control-ui
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] npm ERR! System Linux 3.13.0-53-generic
[ERROR] npm ERR! command "/home/jeiroa/git/espcc-ui/node/node" "/home/jeiroa/git/espcc-ui/node/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! cwd /home/jeiroa/git/espcc-ui
[ERROR] npm ERR! node -v v0.10.38
[ERROR] npm ERR! npm -v 1.4.28
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! 
[ERROR] npm ERR! Additional logging details can be found in:
[ERROR] npm ERR!     /home/jeiroa/git/espcc-ui/npm-debug.log
[ERROR] npm ERR! not ok code 0

and debug log:
8100 error gravity-central-control-ui@0.0.0 postinstall: `cd node_modules/qTip2 && npm run build`
8100 error Exit status 127
8101 error Failed at the gravity-central-control-ui@0.0.0 postinstall script.
8101 error This is most likely a problem with the gravity-central-control-ui package,
8101 error not with npm itself.
8101 error Tell the author that this fails on your system:
8101 error     cd node_modules/qTip2 && npm run build
8101 error You can get their info via:
8101 error     npm owner ls gravity-central-control-ui
8101 error There is likely additional logging output above.
8102 error System Linux 3.13.0-53-generic

It seems that it cannot find npm script.

**Comment by eirslett** [comment]
Hmm... Try the latest release of the plugin, with the node/npm path fix applied! I think that should solve the problem. Feel free to reopen if that doesn't work.

**Comment by jeiroa** [comment]
I have tried version 0.0.25 and I still have problems. Now the error is:

[INFO] Running 'gulp.js package --production --filename=espcc-ui --no-color' in /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build
[INFO] [15:15:40] Dispatching team of highly trained monkeys...
[ERROR] 
[ERROR] module.js:340
[ERROR]     throw err;
[ERROR]     ^
[ERROR] Error: Cannot find module 'gulp-nightwatch'
[ERROR]     at Function.Module._resolveFilename (module.js:338:15)
[ERROR]     at Function.Module._load (module.js:280:25)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build/Gulpfile.js:21:18)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Liftoff.handleArguments (/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build/node_modules/gulp/bin/gulp.js:116:3)
[ERROR]     at Liftoff.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build/node_modules/gulp/node_modules/liftoff/index.js:192:16)
[ERROR]     at module.exports (/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
[ERROR]     at Liftoff.<anonymous> (/home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build/node_modules/gulp/node_modules/liftoff/index.js:185:9)
[ERROR]     at /home/bamboo/bamboo-agent-home/xml-data/build-dir/ESPCC-UI-BT/build/node_modules/gulp/node_modules/liftoff/index.js:159:9

  Same error locally (neither mpn nor nodejs installed) and on bamboo, both Ubuntu 14.04

  Thanks for your help.

**Comment by bmhm** [comment]
Only happens on windows.
