### ISSUE TITLE
Yarn proxy issue

### ISSUE THREAD

**Issue by tschaka1904** [eirslett/frontend-maven-plugin#695]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Using `install-node-and-yarn` and `yarnInheritsProxyConfigFromMaven` and performing a `eslint ./src/main/webapp/*/*.js` leads to `Invalid option '--https-proxy' - perhaps you meant '--parser'?`

**If the current behavior is a bug, please provide the steps to reproduce.**
Using this setup:
![screen shot 2018-02-23 at 12 20 57](https://user-images.githubusercontent.com/5269116/36591970-154a6c66-1894-11e8-8f71-e7990a114467.png)

**What is the expected behavior?**
I can in the:
![screen shot 2018-02-23 at 12 22 30](https://user-images.githubusercontent.com/5269116/36592008-43c55ede-1894-11e8-9e4b-a4348ebeda3a.png)

add a `<yarnInheritsProxyConfigFromMaven>false<yarnInheritsProxyConfigFromMaven/>`, but this feels quite redundant. Maybe you should just be able to define where you want to use the proxy. 

**Please mention your frontend-maven-plugin and operating system version.**
Mac OS High Sierra 10.13.3

**Comment by anasofiapaixao** [comment]
I am having this issue due to the proxy configurations in the super pom. Whenever a proxy is configured in the pom, frontend-maven-plugin appends `--http-proxy` and `--https-proxy` parameters to _every_ yarn command. This means that, when I run e.g. `yarn run lint`, the actual command ends up being `yarn run lint --https-proxy=<proxy> --proxy=<proxy>`, which results in an error.

**Comment by andonu** [comment]
Managed to work around this by merging the test and lint goals together, it seems the plugin just appends the proxy args at the end. From package.json: `"check": "eslint src --format table --ext .js,.jsx,.ts,.tsx --fix && react-scripts test --watchAll=false --passWithNoTests",`

And in maven: `                    <execution>
                        <id>yarn check</id>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                        <phase>test</phase>
                        <configuration>
                            <arguments>run check</arguments>
                            <environmentVariables>
                                <CI>true</CI>
                            </environmentVariables>
                        </configuration>
                    </execution>`

**Comment by mshepel** [comment]
It's resolved in version 1.12.0

**Comment by mvrueden** [comment]
I stumbled upon this today and we are using 1.12.0. So it is still an issue.
